version: 2
updates:
  - package-ecosystem: github-actions
    assignees:
      - dflippojr
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: pip
    assignees:
      - dflippojr
    directory: /
    schedule:
      interval: weekly
