sonar.host.url=https://sonarcloud.io
sonar.organization=dflippojr
sonar.projectKey=dflippojr_.github
sonar.sources=scripts/sync_labels.py
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
